### ISSUE TITLE
'文档编辑’用词不准确。 应该叫‘文本处理’

### ISSUE THREAD

**Issue by zhangwei217245** [jaywcjlove/linux-command#100]
文档不一定只有文本文档， 还有二进制文档啊。 但是列出来的命令都是文本处理的 。

**Comment by jaywcjlove** [comment]
@zhangwei217245 那里的文档编辑？来一个 PR？

**Comment by jaywcjlove** [comment]
@zhangwei217245 那里的文档编辑？来一个 PR？

**Comment by easin-li** [comment]
@zhangwei217245 说的有道理啊

**Comment by jaywcjlove** [comment]
@easin-li 举个例子

**Comment by huckhuang** [comment]
@jaywcjlove 他的意思是说 README 里的“[文档编辑](https://github.com/jaywcjlove/linux-command/blob/d16b220673d0ee7129d2c9a3ccf7b5f621ca5b69/README.md#%E6%96%87%E6%A1%A3%E7%BC%96%E8%BE%91)”应该改成“文本处理”。文档编辑算是文本处理的子集。

**Comment by jaywcjlove** [comment]
@huckhuang 哦，解了，好像是可以改成文本处理。
