### ISSUE TITLE
Pushing code!!  → Err: Cloning into 'node_modules\_gh-pages@2.0.1@gh-pages\.cache\git@github.com!jaywcjlove!linux-command.git'

### ISSUE THREAD

**Issue by liuyang77886** [jaywcjlove/linux-command#101]
◟   Pushing code!!  → Err: Cloning into 'node_modules\_gh-pages@2.0.1@gh-pages\.cache\git@github.com!jaywcjlove!linux-command.git'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by jaywcjlove** [comment]
@liuyang77886 你要干嘛，向我仓库里面提交内容？

**Comment by bzfq21** [comment]
我自己搞错了，对不起对不起

发自我的 iPhone

在 2019年5月11日，下午10:47，小弟调调™ <notifications@github.com<mailto:notifications@github.com>> 写道：


@liuyang77886<https://github.com/liuyang77886> 你要干嘛，向我仓库里面提交内容？

**Comment by jaywcjlove** [comment]
@bzfq21 欢迎更新内容 😄

**Comment by liuyang77886** [comment]
我执行npm start报的错误。或者执行  npm run deploy报的错误

**Comment by jaywcjlove** [comment]
@liuyang77886 你可以执行 `npm run build` 编译本地预览, `npm run start` 执行了 `build`, 并且执行了 `npm run deploy`, 这个命令是向我的仓库 gh-pages 分支提交编译好的 静态页面。

你没有权限向我的仓库提交代码，所以报错了。

**Comment by jaywcjlove** [comment]
@liuyang77886 你可以更改提交的 URL

https://github.com/jaywcjlove/linux-command/blob/daec36f19513c6568d877351125d9bf379198e26/build/deploy.js#L13
