### ISSUE TITLE
Pushing code!! → Err: Cloning into 'node_modules_gh-pages@2.0.1@gh-pages.cache\git@github.com!jaywcjlove!linux-command.git'... Host key verification failed. fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.

### ISSUE THREAD

**Issue by liuyang77886** [jaywcjlove/linux-command#102]
我执行npm start报的错误。或者执行 npm run deploy报的错误

 Pushing code!! → Err: Cloning into 'node_modules_gh-pages@2.0.1@gh-pages.cache\git@github.com!jaywcjlove!linux-command.git'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by jaywcjlove** [comment]
@liuyang77886 https://github.com/jaywcjlove/linux-command/issues/101#issuecomment-491719880
