### ISSUE TITLE
部分图片缺失

### ISSUE THREAD

**Issue by Ice-Hazymoon** [jaywcjlove/linux-command#103]
## Unpkg 上的版本

![image](https://user-images.githubusercontent.com/25239977/57613407-5fe0c680-75a9-11e9-9d6d-7cd57a623574.png)

## GitHub上的版本

![image](https://user-images.githubusercontent.com/25239977/57613443-75ee8700-75a9-11e9-8fe2-27a8fa3c9980.png)

不知道是不是没同步更新的问题， unpkg上的版本部分图片缺失，GitHub上的版本却直接移除了所以图片。

**Comment by jaywcjlove** [comment]
@Ice-Hazymoon 移除了图片，图片导致其它应用提交变大。
