### ISSUE TITLE
chrome插件 - 趋势榜js文件报错，导致页面加载不出来。

### ISSUE THREAD

**Issue by slowlog** [jaywcjlove/linux-command#122]
![WX20190705-160837](https://user-images.githubusercontent.com/16852041/60707876-4de32a80-9f3f-11e9-92a7-0b1a098a1be4.png)

**Comment by jaywcjlove** [comment]
@slowlog  https://github.com/jaywcjlove/oscnews/issues/29 参考这个 issue 应该可以解决

**Comment by slowlog** [comment]
ok，解决了
