### ISSUE TITLE
网路命令分类里面没有ip

### ISSUE THREAD

**Issue by xrfinbupt** [jaywcjlove/linux-command#124]
是我孤陋寡闻了吗
Linux的ip命令和ifconfig类似，但前者功能更强大，并旨在取代后者

**Comment by jaywcjlove** [comment]
@xrfinbupt 欢迎建 PR 共同维护，谢谢！

**Comment by ZhuangZhu-74** [comment]
@xrfinbupt 
你好，你讨论的这个主题是指的在主页的README.md的网络通讯部分没有列出ip命令吗？因为我查看了command目录里是有ip.md这个文件的。

**Comment by jaywcjlove** [comment]
@ZhuangZhu-74 可能是web网站没有搜出来的问题，有 `ip.md` 和 `ifconfig.md` 文件。我好像解决了这个问题。 :)
