### ISSUE TITLE
推荐将github workflows引用的peaceiris/actions-gh-pages@v2.5.0升级至peaceiris/actions-gh-pages@v3

### ISSUE THREAD

**Issue by dingpengyu** [jaywcjlove/linux-command#154]
jaywcjlove您好
当前github workflows在部署的过程中会删除CNAME文件
这是使用/actions-gh-pages@v2.5.0才会出现的问题。
推荐将 peaceiris/actions-gh-pages@v2.5.0升级到 peaceiris/actions-gh-pages@v3
问题即可解决。
谢谢

**Comment by dingpengyu** [comment]
以下是带有删除CNAME的代码例子:
Run peaceiris/actions-gh-pages@v2.5.0 按钮
/usr/bin/docker run --name e87b523f149ca4c7434ff2995a14b5df9f1951_4f77c4 --label e87b52 --workdir /github/workspace --rm -e ACTIONS_DEPLOY_KEY -e PUBLISH_BRANCH -e PUBLISH_DIR -e CNAME -e INPUT_EMPTYCOMMITS -e INPUT_KEEPFILES -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/linux-command/linux-command":"/github/workspace" e87b52:3f149ca4c7434ff2995a14b5df9f1951
INFO: Deploy to dingpengyu/linux-command
INFO: setup with ACTIONS_DEPLOY_KEY
# github.com:22 SSH-2.0-babeld-2de4da3d
Cloning into '/github/home/ghpages_7254'...
Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
rm 'CNAME'

**Comment by jaywcjlove** [comment]
@dingpengyu 我这个项目不需要 CNAME 的

**Comment by dingpengyu** [comment]
> @dingpengyu 我这个项目不需要 CNAME 的

CNAME主要是绑定域名用的

**Comment by jaywcjlove** [comment]
@dingpengyu 我知道，我的域名不是这个库 绑定的，所以这个库不需要 CNAME

**Comment by dingpengyu** [comment]
> @dingpengyu 我知道，我的域名不是这个库 绑定的，所以这个库不需要 CNAME

好的，那么我关闭这个问题。
我在部署的时候经常会自动的删除CNAME，所以才提了这个问题
还以为用的是这个组件。
感谢回复。
