### ISSUE TITLE
Wrong place for Alfred

### ISSUE THREAD

**Issue by wanhuasong** [jaywcjlove/linux-command#158]
Alfred linked to the latest release in README but it was released in 1.2.2

**Comment by ZhuangZhu-74** [comment]
您好！
    我英文不太好，用谷歌在线翻译了一下，结果是

> Alfred链接到README中的最新版本，但它是在1.2.2中发布的。

我觉得这其实也不算矛盾，因为确实最近没有随着版本发布而更新 Alfred 的内容（我不负责这部分），如果您有兴趣可以考虑加入我们来改进 Alfred 的发布，谢谢！

**Comment by Gitfz810** [comment]
![image](https://user-images.githubusercontent.com/38970394/89856104-e9c37900-dbca-11ea-8db1-c50167ff1765.png)
使用 Alfred 跳转到浏览器搜索。使用的是 Alfred 的 1.2.2 版本

**Comment by MuYunyun** [comment]
where to download alfred workflow plugin? The following link is to jump to the release page.

![image](https://user-images.githubusercontent.com/19354791/91387277-7f1b6a00-e867-11ea-90a1-6b58a3035fcc.png)

**Comment by jaywcjlove** [comment]
@MuYunyun https://github.com/jaywcjlove/linux-command/releases/tag/v1.2.2

**Comment by ZhuangZhu-74** [comment]
> where to download alfred workflow plugin? The following link is to jump to the release page.
> 
> ![image](https://user-images.githubusercontent.com/19354791/91387277-7f1b6a00-e867-11ea-90a1-6b58a3035fcc.png)

请打开 https://github.com/jaywcjlove/linux-command/releases/tag/v1.2.2  ，可以找到。

**Comment by MuYunyun** [comment]
> @MuYunyun https://github.com/jaywcjlove/linux-command/releases/tag/v1.2.2

thanks
