### ISSUE TITLE
项目网址(https://git.io/linux)打不开

### ISSUE THREAD

**Issue by ShadowThree** [jaywcjlove/linux-command#191]
![image](https://user-images.githubusercontent.com/41199004/93542014-9216eb00-f98a-11ea-8923-bd4f63215d4a.png)

**Comment by jaywcjlove** [comment]
@ShadowThree 

估计你需要翻墙，有个国内镜像 https://jaywcjlove.gitee.io/linux-command/

**Comment by ShadowThree** [comment]
这么好的学习网站也被墙。。。
镜像可以了
多谢哈
