### ISSUE TITLE
fork后我如何搭建我的网页版本

### ISSUE THREAD

**Issue by xiangfeigao** [jaywcjlove/linux-command#193]
已经fork了，国内还是用gitee 比较好用。
小白的问题：
为什么我fork后，gitee page页面不能访问404错误，请不吝赐教。

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/93737039-a53ceb80-fc14-11ea-8d4b-ad77592cdd06.png)

![image](https://user-images.githubusercontent.com/1680273/93737056-b4bc3480-fc14-11ea-9091-dd0604a18350.png)

@xiangfeigao 截图给你了。
