### ISSUE TITLE
CentOS7 中管理防火墙配置的工具

### ISSUE THREAD

**Issue by jerrybendy** [jaywcjlove/linux-command#2]
你好，CentOS 7 中有一个管理防火墙的命令行工具 `firewall-cmd`，具体用法我也不是很清楚，只知道

* 添加规则 `firewall-cmd --permanent --zone=public --add-port=80/tcp`
* 删除规则 `firewall-cmd --permanent --zone=public --remove-port=80/tcp`
* 重新载入 `firewall-cmd --reload`

可否考虑把这个命令加进去呢？

**Comment by jaywcjlove** [comment]
已经添加 [firewall-cmd.md](https://github.com/jaywcjlove/linux-command/blob/master/command/firewall-cmd.md)
