### ISSUE TITLE
alfred 无法使用哈。

### ISSUE THREAD

**Issue by TomatoFryEggs** [jaywcjlove/linux-command#22]

**Comment by TomatoFryEggs** [comment]
alfred3

**Comment by jaywcjlove** [comment]
alfred3 可以使用 @TomatoFryEggs

**Comment by TomatoFryEggs** [comment]
<img width="563" alt="screenshot 2017-04-28 09 14 00" src="https://cloud.githubusercontent.com/assets/9395814/25510501/1f7f74f8-2bf3-11e7-85a0-efc56f398ba4.png">
<img width="560" alt="screenshot 2017-04-28 09 13 51" src="https://cloud.githubusercontent.com/assets/9395814/25510500/1f76977a-2bf3-11e7-82cf-565086d1d336.png">

**Comment by TomatoFryEggs** [comment]
<img width="1174" alt="screenshot 2017-04-28 09 27 58" src="https://cloud.githubusercontent.com/assets/9395814/25510779/42b7ee6c-2bf5-11e7-95b0-81831175f741.png">

**Comment by jaywcjlove** [comment]
@TomatoFryEggs 

噢这个是用node 写的，你本机node 版本太低，不支持ES6 语法 ？

**Comment by TomatoFryEggs** [comment]
@jaywcjlove sierra10.12.4，难道要另外安装node？

**Comment by TomatoFryEggs** [comment]
谢谢，升级后问题解决。
