### ISSUE TITLE
建议添加Arch系常用命令

### ISSUE THREAD

**Issue by TongReG** [jaywcjlove/linux-command#224]
目前都没有Pacman...

**Comment by jaywcjlove** [comment]
@TongReG 欢迎提交 PR

**Comment by conglinyizhi** [comment]
@TongReG 我已经添加了 pacman 指令 #487 

因为我使用 Arch Linux 衍生的 Linux 版本时间不太长，所以我不太清楚有什么指令可以添加，可以给一些建议吗？谢谢

**Comment by conglinyizhi** [comment]
嘿！我已经添加了 pacman.md (#487 ) 和更多指令，可以请您关闭这个 issue 吗？ @TongReG
