### ISSUE TITLE
请问web版构建所需的环境？

### ISSUE THREAD

**Issue by githubitnow** [jaywcjlove/linux-command#241]
感谢提供这么好的命令参考工具！

我想在单位的内网（不能连接internet）把web版架起来，方便大家使用。

请问架设过程需要什么样的操作系统、应用软件或开发环境呢？

web开发我基本不会，所以具体需求、步骤越详细越好，非常感谢！

**Comment by jaywcjlove** [comment]
@githubitnow 克隆 `gh-pages` 分支，打开 `index.html` 就可以使用了

```bash
git clone git@github.com:jaywcjlove/linux-command.git -b gh-pages
```

**Comment by jaywcjlove** [comment]
@githubitnow 如果你要新增内容。

1. 克隆 master 分支

```bash
git clone https://github.com/jaywcjlove/linux-command.git
```

2. 安装 `node.js` 环境
3. 进入 `linux-command` 目录，安装依赖 `npm install`
4. 将新增的命令文件，放到 `command` 目录，命名为 `命令名称.md`， 
5. 编译 `html`，运行编译命令 `npm run build`，生成的静态文件在目录下的 `.deploy` 文件夹
6. 进入 `.deploy` 文件夹，打开 `index.html` 文件在浏览器中预览

**Comment by githubitnow** [comment]
谢谢！

但是我是要在内网（不能连接Internet）的局域网里架设这个，没法直接使用git命令来clone

应该怎么做呢？

**Comment by jaywcjlove** [comment]
@githubitnow 局域网跟有没有git 没有关系吧，那你直接切换到 [gh-pages](https://github.com/jaywcjlove/linux-command/tree/gh-pages) 分支，下载代码就可以了吧。

**Comment by githubitnow** [comment]
好的，我先试试，不懂再向你请教

再次感谢！

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/117255865-bcb3a680-ae7c-11eb-9e05-a0fa623eb1f7.png)
@githubitnow
