### ISSUE TITLE
Dash版本没法解压

### ISSUE THREAD

**Issue by YouLanjie** [jaywcjlove/linux-command#255]
下载了Dash版本的压缩包后，解压时出现下面问题：
![error](https://user-images.githubusercontent.com/66255345/121014672-cf4b3380-c7cc-11eb-9166-3b5b4c06e562.png)
也不知道为什么

**Comment by jaywcjlove** [comment]
https://jaywcjlove.github.io/linux-command/linux-command.docset.zip

@YouLanjie 不知道 你什么解压软件，我在 mac OS 上测试了，没有什么问题。

**Comment by YouLanjie** [comment]
当初用的是ubuntu的自带解压软件，后来换了系统就没有这个问题了

**Comment by dchen23** [comment]
我再 linux 和 mac 都试了，好像都没法解压。unzip 命令也不行

**Comment by jaywcjlove** [comment]
@dchen23 用 Safari 下载？

**Comment by dchen23** [comment]
Safari 下载可以使用，非常感谢！
