### ISSUE TITLE
微信小程序版本

### ISSUE THREAD

**Issue by MatzYang** [jaywcjlove/linux-command#260]
微信小程序版本来啦！简约的风格，方便的操作，欢迎体验~~

![image](https://user-images.githubusercontent.com/1445225/123251478-d50b7d80-d51d-11eb-80e4-01e18212fc4d.png)

![image](https://user-images.githubusercontent.com/1445225/123251650-097f3980-d51e-11eb-822a-91190942a3ce.png)

![image](https://user-images.githubusercontent.com/1445225/123251677-11d77480-d51e-11eb-9e29-a5b7c44fa285.png)

![image](https://user-images.githubusercontent.com/1445225/123251758-24ea4480-d51e-11eb-8d49-ba7010112fbd.png)

![image](https://user-images.githubusercontent.com/1445225/123251791-2d427f80-d51e-11eb-96c9-1f7079b84db1.png)

**Comment by MatzYang** [comment]
@jaywcjlove 能否放到首页README.md里面方便大家使用

**Comment by jaywcjlove** [comment]
@MatzYang 已经添加，你看看是否正确 

thx!

**Comment by MatzYang** [comment]
@jaywcjlove 嗯嗯，是的

**Comment by StephenJose-Dai** [comment]
小程序源码有开源吗？
