### ISSUE TITLE
使用手机搜索的话  第一个搜索结果会被遮挡住

### ISSUE THREAD

**Issue by iiivii** [jaywcjlove/linux-command#268]
![wangchujiang com_linux-command_list html(Galaxy S5) (1)](https://user-images.githubusercontent.com/41566909/129176155-c4b35ce4-2610-4eda-8c67-af09454bb4df.png)
如图所示，第一个搜索结果被搜索栏给遮住了。

**Comment by iiivii** [comment]
还有一个，网页上开源中国Web版的404了。

**Comment by jaywcjlove** [comment]
@iiivii 因为服务器在维护 https://gitee.com/jaywcjlove/linux-command/pages
