### ISSUE TITLE
Gitee Pages 镜像部署【违禁违规】问题

### ISSUE THREAD

**Issue by xiaokaixuan** [jaywcjlove/linux-command#283]
**https://jaywcjlove.gitee.io/linux-command/ 还是404**

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/132033621-6b737c11-133b-4381-9ab5-8df902fa656a.png)

**Comment by jaywcjlove** [comment]
https://gitee.com/jaywcjlove/linux-command/issues/I47YT8

**Comment by leisurelyclouds** [comment]
可以 二分法找到对应的位置 就是要多提交几次

**Comment by xiaokaixuan** [comment]
> 可以 二分法找到对应的位置 就是要多提交几次

没必要了 就用github行了

**Comment by alone-wolf** [comment]
谁用gitee啊，github不香吗

**Comment by jaywcjlove** [comment]
其实已经有很多人部署了我们这个网站，还有魔改的。 

[`linux.devonline.net`](http://linux.devonline.net/)，[`linux.ftqq.com`](https://linux.ftqq.com/)，[`linux.gaomeluo.com`](https://linux.gaomeluo.com)，[`atoolbox.net`](http://www.atoolbox.net/Tool.php?Id=826)，[`xiaoshanseo.com`](https://tools.xiaoshanseo.com/Tools/linux-command/)，[`262235.xyz`](https://262235.xyz/linux-command/)，[`cmsblogs.cn`](https://linux.cmsblogs.cn/)，[`loquy.cn`](https://www.loquy.cn/linux-command/)，[`bqrdh.com`](https://tools.bqrdh.com/linux-command/)，[`buyao.vip`](https://demo.buyao.vip/linux/)，[`hezhiqiang.gitbook.io`](https://hezhiqiang.gitbook.io/linux/)

**Comment by jaywcjlove** [comment]
Gitee 看上去无法解决，于是想到提供一个 docker 镜像，本地快速部署，直接本地访问 :) 完美！

## Docker

[![Docker Image Version (latest by date)](https://img.shields.io/docker/v/wcjiang/linux-command?logo=docker)](https://hub.docker.com/r/wcjiang/linux-command) [![Docker Image Size (latest by date)](https://img.shields.io/docker/image-size/wcjiang/linux-command?logo=docker)](https://hub.docker.com/r/wcjiang/linux-command) [![Docker Pulls](https://img.shields.io/docker/pulls/wcjiang/linux-command?logo=docker)](https://hub.docker.com/r/wcjiang/linux-command)

轻松通过 docker 部署 linux-command 网站。

```bash
docker pull wcjiang/linux-command
```

```bash
docker run --name linux-command --rm -d -p 9665:80 wcjiang/linux-command:latest
# Or
docker run --name linux-command -itd -p 9665:80 wcjiang/linux-command:latest
```

在浏览器中访问以下 URL

```bash
http://localhost:9665/
```

**Comment by zyimm** [comment]
> 其实已经有很多人部署了我们这个网站，还有魔改的。
> 
> [`linux.devonline.net`](http://linux.devonline.net/)，[`linux.ftqq.com`](https://linux.ftqq.com/)，[`linux.gaomeluo.com`](https://linux.gaomeluo.com)，[`atoolbox.net`](http://www.atoolbox.net/Tool.php?Id=826)，[`xiaoshanseo.com`](https://tools.xiaoshanseo.com/Tools/linux-command/)，[`262235.xyz`](https://262235.xyz/linux-command/)，[`cmsblogs.cn`](https://linux.cmsblogs.cn/)，[`loquy.cn`](https://www.loquy.cn/linux-command/)，[`bqrdh.com`](https://tools.bqrdh.com/linux-command/)，[`buyao.vip`](https://demo.buyao.vip/linux/)，[`hezhiqiang.gitbook.io`](https://hezhiqiang.gitbook.io/linux/)

还有我：[linux.zyimm.com/](http://linux.zyimm.com)

**Comment by jaywcjlove** [comment]
@zyimm 添加到 README.md 上了

**Comment by kindevil** [comment]
> 其实已经有很多人部署了我们这个网站，还有魔改的。
> 
> [`linux.devonline.net`](http://linux.devonline.net/)，[`linux.ftqq.com`](https://linux.ftqq.com/)，[`linux.gaomeluo.com`](https://linux.gaomeluo.com)，[`atoolbox.net`](http://www.atoolbox.net/Tool.php?Id=826)，[`xiaoshanseo.com`](https://tools.xiaoshanseo.com/Tools/linux-command/)，[`262235.xyz`](https://262235.xyz/linux-command/)，[`cmsblogs.cn`](https://linux.cmsblogs.cn/)，[`loquy.cn`](https://www.loquy.cn/linux-command/)，[`bqrdh.com`](https://tools.bqrdh.com/linux-command/)，[`buyao.vip`](https://demo.buyao.vip/linux/)，[`hezhiqiang.gitbook.io`](https://hezhiqiang.gitbook.io/linux/)

我也部署了 [`linux.vovuo.com`](linux.vovuo.com)

**Comment by wizardforcel** [comment]
gitee那边可以写个程序，把所有汉字都转成html实体。

**Comment by jaywcjlove** [comment]
@wizardforcel 没有必要懒得搞，有一个地方弄就好了

**Comment by tangm421** [comment]
国产各种审查甚是恶心:vomiting_face:

**Comment by gigberg** [comment]
> 其实已经有很多人部署了我们这个网站，还有魔改的。
> 
> [`linux.devonline.net`](http://linux.devonline.net/)，[`linux.ftqq.com`](https://linux.ftqq.com/)，[`linux.gaomeluo.com`](https://linux.gaomeluo.com)，[`atoolbox.net`](http://www.atoolbox.net/Tool.php?Id=826)，[`xiaoshanseo.com`](https://tools.xiaoshanseo.com/Tools/linux-command/)，[`262235.xyz`](https://262235.xyz/linux-command/)，[`cmsblogs.cn`](https://linux.cmsblogs.cn/)，[`loquy.cn`](https://www.loquy.cn/linux-command/)，[`bqrdh.com`](https://tools.bqrdh.com/linux-command/)，[`buyao.vip`](https://demo.buyao.vip/linux/)，[`hezhiqiang.gitbook.io`](https://hezhiqiang.gitbook.io/linux/)

请问你是怎么检索到这些相关网站的,,怎样才能知道所有部署某这个项目的网站呢,,有什么搜索关键字吗?

**Comment by eccsatan** [comment]
不要考虑gitee了，就是个垃圾

**Comment by ZhYaL** [comment]
没办法，国内就是这样的😭😭

**Comment by li7355608** [comment]
可能触发关键词了，我们有最先进的过滤系统，管你对错都给你删了
