### ISSUE TITLE
我想请问import这个仓库后怎么部署网页了 还是小白 谢谢

### ISSUE THREAD

**Issue by wqcblog** [jaywcjlove/linux-command#290]

**Comment by jaywcjlove** [comment]
@wqcblog 如果你只想部署静态网站，直接克隆 gh-pages 分支就可以了。

https://github.com/jaywcjlove/linux-command/tree/gh-pages

**Comment by jaywcjlove** [comment]
## Docker

[![Docker Image Version (latest by date)](https://img.shields.io/docker/v/wcjiang/linux-command?logo=docker)](https://hub.docker.com/r/wcjiang/linux-command) [![Docker Image Size (latest by date)](https://img.shields.io/docker/image-size/wcjiang/linux-command?logo=docker)](https://hub.docker.com/r/wcjiang/linux-command) [![Docker Pulls](https://img.shields.io/docker/pulls/wcjiang/linux-command?logo=docker)](https://hub.docker.com/r/wcjiang/linux-command)

轻松通过 docker 部署 linux-command 网站。

```bash
docker pull wcjiang/linux-command
```

```bash
docker run --name linux-command --rm -d -p 9665:80 wcjiang/linux-command:latest
# Or
docker run --name linux-command -itd -p 9665:80 wcjiang/linux-command:latest
```

在浏览器中访问以下 URL

```bash
http://localhost:9665/
```
