### ISSUE TITLE
你好，这个Linux命令可以有PDF版本吗

### ISSUE THREAD

**Issue by zailushan** [jaywcjlove/linux-command#320]

**Comment by jaywcjlove** [comment]
@zailushan 没有

**Comment by conglinyizhi** [comment]
嘿，我发现这个 issue 已经存在一段时间了，虽然我目前也没有 PDF 版本，但是我找到了其他信息，值得一看：
#392 
另外，如果上面提到的 issue 已经解决了您的问题，请及时关闭这个 issue，谢谢～

**Comment by jaywcjlove** [comment]
- https://github.com/jaywcjlove/linux-command/issues/392
