### ISSUE TITLE
可以提供raycast版本吗？

### ISSUE THREAD

**Issue by harisonkhlil** [jaywcjlove/linux-command#338]

**Comment by jaywcjlove** [comment]
@harisonkhlil 我看了一下这个工具搞个扩展是 react 挺简单的，我来试一试

**Comment by jaywcjlove** [comment]
@harisonkhlil 我确定非常简单，花了俩小时看文档将扩展撸出来了，但是不一定能提交到商店中。我已经发起 PR，等待审核。

- https://github.com/raycast/extensions/pull/1032

![image](https://user-images.githubusercontent.com/1680273/156889052-ab2f4ac5-85ba-448e-9879-771ee5db2726.png)

![image](https://user-images.githubusercontent.com/1680273/156889067-e2496ece-cfa8-4f87-9e36-26599360ab60.png)

![image](https://user-images.githubusercontent.com/1680273/156889078-17e0a936-e7f2-4be3-8a84-68ad63e915dc.png)

![image](https://user-images.githubusercontent.com/1680273/156889091-c1b4e74f-6ddf-412a-ad16-9327290614ae.png)

**Comment by jaywcjlove** [comment]
@harisonkhlil https://github.com/raycast/extensions/pull/1032#pullrequestreview-903453757

看吧这个中文人家不合并。要不我造个 `raycast` 的轮子？工程量有点大。

**Comment by jaywcjlove** [comment]
@harisonkhlil https://github.com/raycast/extensions/pull/1032#pullrequestreview-907119770

要合并了。

**Comment by jaywcjlove** [comment]
@harisonkhlil https://www.raycast.com/jaywcjlove/linux-command

可以使用了
