### ISSUE TITLE
部署时遇到的问题，解决方案与大家共享

### ISSUE THREAD

**Issue by immoke** [jaywcjlove/linux-command#341]
大神们好，感谢各位大神开源这么好的linux学习平台。
之前部署1.7.1版本，很顺利，昨天升级到1.8.3时，遇到了一些问题，希望把我的部署经验分享给大家，避免大家走弯路。

环境：
腾讯轻量云，CentOS7.9，宝塔面板7.9(不重要)，nodev16.14.0，npm8.5.2，linux-command1.8.3

1）npm install时，卡在：reify:rxjs: timing reifyNode:node_modules/rxjs Completed in 4682ms
解决方法：不确定问题点在哪，换过源，删过node_modules的缓存目录。最后还是看运气。主要还是网络的问题。

2）EACCES: permission denied, open ‘/www/wwwroot/linux.mmoke.com/dist/data.json’
在linux-command根目录下，执行sudo chown -R $(whoami) .

3）ENOTDIR: not a directory, scandir ‘/www/wwwroot/linux.mmoke.com/.deploy/.user.ini’
宝塔面板因为有.user.ini。不能用.deploy当作WEB目录，必须移动。

4）js脚本本地化
部署1.8.3版本时发现（之前用的1.7.1），为了增加页面内容复制的功能，引用了网上的一个js文件。直接增加网页的打开速度。
`wget -O $webdir/www/js/copy-to-clipboard.umd.js "https://unpkg.com/@uiw/copy-to-clipboard/dist/copy-to-clipboard.umd.js"
wget -O $webdir/www/js/copy-to-clipboard.umd.js.map "https://unpkg.com/@uiw/copy-to-clipboard@1.0.12/dist/copy-to-clipboard.umd.js.map"
chown www:www $webdir/www/js -R
sed -i "s/https:\/\/unpkg.com\/\@uiw\/copy-to-clipboard\/dist\/copy-to-clipboard.umd.js/\/js\/copy-to-clipboard.umd.js/g" $webdir/linux-command/template/details.ejs`

另外，提几个小建议：
1、我看到作者给多个人回复说，可以自由修改。其实我个人很支持开源，基本上我不会选择去掉版权。只是，您这里的外部链接太多了。很理解您想推广的心情。作为一个个人学习用，给朋友分享的小站点，我们希望仅仅有作者版权链接，而没有那么多的推广链接，比如百度统计代码，Alfred、Dash、开源中国等等。
2、我是部署在公司内网环境，无法访问外网，因此是否可以减少外部cdn文件的引用？
3、请问超链接是否可以改成_blank模式？

如上，个人小站点https://linux.mmoke.com，保留了右上角的github超链接，欢迎访问。

**Comment by jaywcjlove** [comment]
@immoke 

- [x] 移除了百度统计
- [x] 删除了 cdn 的引入
- [ ] 那些地方改成 _blank 呢？

**Comment by immoke** [comment]
> 

感谢大神能接受我的小建议。
因为有些超链接我去掉了，以我剩下的链接为例哈：

首页：Github | 短地址：https://git.io/linux，这两个链接是未带_blank的；
contributors.html：这里有2个超链接，没有带_blank的；

_blank这个可能单纯的是个人的强迫症，再次感谢作者开源如此优秀的平台。

**Comment by jaywcjlove** [comment]
@immoke 已经全部解决。
