### ISSUE TITLE
支持 Dash 的自动更新 feed

### ISSUE THREAD

**Issue by imvkmark** [jaywcjlove/linux-command#343]
你好, 我添加了一个不定期更新的 feed

https://raw.githubusercontent.com/imvkmark/dash-docsets/master/linux-command-docset.xml

在 dash 中可以订阅, 有新的文档可以自动更新为最新版

![image](https://user-images.githubusercontent.com/150127/157821194-04fc888f-2f6a-42ff-94d6-2a0dfcefba12.png)

希望能够有所帮助:

https://github.com/imvkmark/dash-docsets

**Comment by jaywcjlove** [comment]
@imvkmark 你可以添加 GitHub action 自动更新

**Comment by imvkmark** [comment]
更新的时候还需要更新版本号 / 更新 xml 文件, 更新 release, 提交 git 记录, 同样是多项目操作, 会比较复杂一点, 暂时还没有想到处理方案

**Comment by jaywcjlove** [comment]
@imvkmark 只要生成下面代码，dash 就可以订阅？

```xml
<entry>
    <version>1.8.3</version>
    <url>https://github.com/imvkmark/dash-docsets/releases/download/lc-1.8.3/linux-command.docset.tar.gz</url>
</entry>
```

**Comment by imvkmark** [comment]
dash 的更新机制是把 `version` 当成字符串版本, 版本不一致则更新
最好方式是检测项目 tag 标签, 根据 tag 自动生成并提交同时更新 feed 文件即可
