### ISSUE TITLE
time命令存疑

### ISSUE THREAD

**Issue by zchrissirhcz** [jaywcjlove/linux-command#352]
https://wangchujiang.com/linux-command/c/time.html

![图片](https://user-images.githubusercontent.com/3831847/162969629-4d36824b-94fe-4a7c-8387-8b0bfea41239.png)

本地ubuntu20.04，运行 `time` 得到的输出不一样：
```
time -help 
zsh: command not found: -help
-help  0.00s user 0.00s system 82% cpu 0.002 total
```
![图片](https://user-images.githubusercontent.com/3831847/162969782-4ae50aab-64da-4bb2-8ead-7ca856fe4f94.png)

**Comment by jaywcjlove** [comment]
![](https://user-images.githubusercontent.com/1680273/162971399-331cf133-b0af-4d21-8af4-fc0bec4ffbbc.png)

我这 centos 的

@zchrissirhcz

**Comment by zchrissirhcz** [comment]
和系统没有太大关系，和用的shell有关系。我是 zsh，你的应该是 bash。
不同的shell环境下，time的输出不一样，因为time是shell内置的。

**Comment by conglinyizhi** [comment]
我已经按照这个 issue 的提议更新了，能否关闭它呢？
