### ISSUE TITLE
gh-pages的ack页面超链接有误

### ISSUE THREAD

**Issue by Gzh0821** [jaywcjlove/linux-command#353]
![image](https://user-images.githubusercontent.com/87368454/163130760-aff5b893-8a73-41b2-a8f3-6296457acdbf.png)
会跳转到主页而非beyondgrep.com页面上。
![image](https://user-images.githubusercontent.com/87368454/163131421-2650926d-6df3-4036-a515-11b36fd5942c.png)

可能是该页面javascript函数的bug导致的问题。

**Comment by jaywcjlove** [comment]
@Gzh0821 thx! 已修复
