### ISSUE TITLE
没有 setsid 命令

### ISSUE THREAD

**Issue by funnypro** [jaywcjlove/linux-command#37]
如题

setsid 似乎可以让执行的命令的PPID变为1

**Comment by huckhuang** [comment]
Known references:
- [setsid at die.net](https://linux.die.net/man/2/setsid)
- [setsid at man7.org](http://man7.org/linux/man-pages/man2/setsid.2.html)
- [setsid at opengroup.org](http://pubs.opengroup.org/onlinepubs/009695399/functions/setsid.html)

**Comment by jaywcjlove** [comment]
👍
