### ISSUE TITLE
请问域名挂了吗

### ISSUE THREAD

**Issue by Vector6662** [jaywcjlove/linux-command#384]
https://wangchujiang.com/linux-command/
没法访问了

**Comment by jaywcjlove** [comment]
@Vector6662 要梯子

**Comment by Vector6662** [comment]
> @Vector6662 要梯子
> 
> 下面有一堆国内镜像网站
> 
> [linux.devonline.net](http://linux.devonline.net/)，[linux.ftqq.com](https://linux.ftqq.com/)，[linux.gaomeluo.com](https://linux.gaomeluo.com/)，[atoolbox.net](http://www.atoolbox.net/Tool.php?Id=826)，[xiaoshanseo.com](https://tools.xiaoshanseo.com/Tools/linux-command/)，[262235.xyz](https://262235.xyz/linux-command/)，[cmsblogs.cn](https://linux.cmsblogs.cn/)，[loquy.cn](https://www.loquy.cn/linux-command/)，[bqrdh.com](https://tools.bqrdh.com/linux-command/)，[buyao.vip](https://demo.buyao.vip/linux/)，[hezhiqiang.gitbook.io](https://hezhiqiang.gitbook.io/linux/)，[linux.mmoke.com](https://linux.mmoke.com/), [luojianjun.cn](https://luojianjun.cn/linux-command/), [man.zch.ooo](https://man.zch.ooo/)

我挂了梯子，还是没法访问

**Comment by jaywcjlove** [comment]
@Vector6662 你也可以轻松通过 docker 部署 linux-command 网站。

```
docker pull wcjiang/linux-command
# Or
docker pull ghcr.io/jaywcjlove/linux-command:latest
docker run --name linux-command --rm -d -p 9665:3000 wcjiang/linux-command:latest
# Or
docker run --name linux-command -itd -p 9665:3000 wcjiang/linux-command:latest
# Or
docker run --name linux-command -itd -p 9665:3000 ghcr.io/jaywcjlove/linux-command:latest
```
在浏览器中访问以下 URL

```
http://localhost:9665/
```

**Comment by jaywcjlove** [comment]
> > @Vector6662 要梯子
> > 下面有一堆国内镜像网站
> > [linux.devonline.net](http://linux.devonline.net/)，[linux.ftqq.com](https://linux.ftqq.com/)，[linux.gaomeluo.com](https://linux.gaomeluo.com/)，[atoolbox.net](http://www.atoolbox.net/Tool.php?Id=826)，[xiaoshanseo.com](https://tools.xiaoshanseo.com/Tools/linux-command/)，[262235.xyz](https://262235.xyz/linux-command/)，[cmsblogs.cn](https://linux.cmsblogs.cn/)，[loquy.cn](https://www.loquy.cn/linux-command/)，[bqrdh.com](https://tools.bqrdh.com/linux-command/)，[buyao.vip](https://demo.buyao.vip/linux/)，[hezhiqiang.gitbook.io](https://hezhiqiang.gitbook.io/linux/)，[linux.mmoke.com](https://linux.mmoke.com/), [luojianjun.cn](https://luojianjun.cn/linux-command/), [man.zch.ooo](https://man.zch.ooo/)
> 
> 我挂了梯子，还是没法访问

梯子免费的吧 :)

**Comment by Vector6662** [comment]
> > > @Vector6662 要梯子
> > > 下面有一堆国内镜像网站
> > > [linux.devonline.net](http://linux.devonline.net/)，[linux.ftqq.com](https://linux.ftqq.com/)，[linux.gaomeluo.com](https://linux.gaomeluo.com/)，[atoolbox.net](http://www.atoolbox.net/Tool.php?Id=826)，[xiaoshanseo.com](https://tools.xiaoshanseo.com/Tools/linux-command/)，[262235.xyz](https://262235.xyz/linux-command/)，[cmsblogs.cn](https://linux.cmsblogs.cn/)，[loquy.cn](https://www.loquy.cn/linux-command/)，[bqrdh.com](https://tools.bqrdh.com/linux-command/)，[buyao.vip](https://demo.buyao.vip/linux/)，[hezhiqiang.gitbook.io](https://hezhiqiang.gitbook.io/linux/)，[linux.mmoke.com](https://linux.mmoke.com/), [luojianjun.cn](https://luojianjun.cn/linux-command/), [man.zch.ooo](https://man.zch.ooo/)
> > 
> > 
> > 我挂了梯子，还是没法访问
> 
> 梯子免费的吧 :)

给钱的🤣🤣🤣，难道买了个免费梯子。我看看怎么搞。谢谢大佬！

**Comment by jaywcjlove** [comment]
@Vector6662 我也不知道，我的梯子很坚挺，

国内镜像也玩不了，不知道哪里的问题 https://github.com/jaywcjlove/linux-command/issues/283

**Comment by Vector6662** [comment]
> @Vector6662 我也不知道，我的梯子很坚挺，
> 
> 国内镜像也玩不了，不知道哪里的问题 #283

哎难顶。。。谢谢大佬，我就用您提供的镜像

**Comment by Crazyokd** [comment]
镜像可以，但梯子不行（不是免费的）

**Comment by jaywcjlove** [comment]
@Crazyokd 说明 土啬 越来越厉害了

**Comment by lavaicer** [comment]
> @Crazyokd 说明 土啬 越来越厉害了

试过Cloudflare的免费CDN吗，我记得以前试过，正常访问
有一些issus已经解决了，师傅顺便关掉吧，我打开好几个结果都是已经解决了的
