### ISSUE TITLE
建议添加目录

### ISSUE THREAD

**Issue by james-wangx** [jaywcjlove/linux-command#398]
有些命令文档写的很详细，但是太长了没有目录不方便分类和查找。
例如awk这个命令：https://wangchujiang.com/linux-command/c/awk.html

**Comment by jaywcjlove** [comment]
@james-wangx 这是一个好的建议，我在这里：https://github.com/jaywcjlove/idoc 已经实现过了，也许有空我看如何集成它

**Comment by james-wangx** [comment]
> @james-wangx 这是一个好的建议，我在这里：https://github.com/jaywcjlove/idoc 已经实现过了，也许有空我看如何集成它

期待更新~
