### ISSUE TITLE
tgz 打包报错

### ISSUE THREAD

**Issue by gclm** [jaywcjlove/linux-command#412]
[Error [TarStreamError]: ENOENT: no such file or directory, stat **linux-command.docset/Contents/Resources/docSet.dsidx-journal** 这个是如何产生的啊

**Comment by gclm** [comment]
我看我本地还是我自己的github action 没出现这个啊

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/linux-command/blob/ad6b52163a0234c0479cd0d5251f9c51c1eca92d/scripts/dash.mjs#L55-L72

这是一个sqlite 文件。

**Comment by gclm** [comment]
其实我有点的迷的地方就在这里，按照await 的原理，只有buildApi执行完毕才会到压缩这里，但是目前看这里并没有执行完毕就到了压缩这里

**Comment by jaywcjlove** [comment]
@gclm 好像可以了

**Comment by gclm** [comment]
<img width="2259" alt="image" src="https://user-images.githubusercontent.com/27618687/187405156-361d6029-76dc-4a77-9a54-a82254534a51.png">
但是我看着两个好像没区别啊

**Comment by gclm** [comment]
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/27618687/187413564-30639a46-4f66-4047-8618-e4607e29e2e0.png">
我打印了一下发现一样，没发现有啥区别。唯一区别就是拼接方案不一样。
