### ISSUE TITLE
docker 生成的镜像不支持arm

### ISSUE THREAD

**Issue by webphper** [jaywcjlove/linux-command#454]

**Comment by jaywcjlove** [comment]
@webphper 我苹果 M1 支持，其它不知道怎么测试

**Comment by webphper** [comment]
我的也是m1,能用。但是容器启动后，有不兼容的提示

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/203349183-935128db-7349-4b48-a21b-6446d41d7c05.png)

我测试了一下可以的样子
@webphper

**Comment by jaywcjlove** [comment]
@webphper 尝试多平台编译都失败需要帮助，我本地启动没有问题

**Comment by jaywcjlove** [comment]
<img width="592" alt="image" src="https://user-images.githubusercontent.com/1680273/203384952-84cbc58b-f942-4830-a799-2f35d86c85ed.png">

@webphper 测试好了，你可以测试一哈

**Comment by staugur** [comment]
```
libcontainer: container start initialization failed: standard_init_linux.go:224: exec user process caused "exec format error"

standard_init_linux.go:224: exec user process caused "exec format error" 
```

虽然linux-command本身多架构支持arm，但是依赖的[docker-static-website](https://hub.docker.com/r/lipanski/docker-static-website/tags)仅支持amd，所以还是报错。

**Comment by jaywcjlove** [comment]
[joseluisq/static-web-server](https://hub.docker.com/r/joseluisq/static-web-server/) 这个有 2.36MB

[lipanski/docker-static-website](https://hub.docker.com/r/lipanski/docker-static-website/tags) 只有 88 KB

@staugur

**Comment by staugur** [comment]
关键它在ARM下报错，或许按照文章试试：
```
FROM busybox:1.36

# Create a non-root user to own the files and run our server
RUN adduser -D static
USER static
WORKDIR /home/static

# Copy the static website
# Use the .dockerignore file to control what ends up inside the image!
COPY ./.deploy .

# Run BusyBox httpd
CMD ["busybox", "httpd", "-f", "-v", "-p", "3000"]
```

**Comment by jaywcjlove** [comment]
@staugur 我将 https://hub.docker.com/r/wcjiang/docker-static-website 进行了重新编译

给它也编译了俩版本，不确定能否解决你的问题，欢迎帮忙测试一哈

![image](https://user-images.githubusercontent.com/1680273/224926036-a47b8e20-83c5-480e-8c16-2c0cece52fb0.png)

**Comment by jaywcjlove** [comment]
@webphper 已经发布了，你重新测试一下看看？

```bash
$ docker pull wcjiang/linux-command:latest
```

**Comment by staugur** [comment]
ARM架构下运行正常！

**Comment by jaywcjlove** [comment]
@staugur thx!
