### ISSUE TITLE
按照词条gcc -c -o 编译，无法通过

### ISSUE THREAD

**Issue by huaji0353** [jaywcjlove/linux-command#46]
理论上.o文件经过-o编译选项后是可以直接生成exec文件
但是实际上需要一堆crt链接才能通过。这样很容易误入歧途
gcc -v 了解一下

**Comment by jaywcjlove** [comment]
@huaji0353 提交个 PR ?

**Comment by huckhuang** [comment]
@huaji0353 你好，我想知道你是否想表述的是命令功能说明缺少使用 gcc 编译时的内部过程的阐述？
据我浅薄的知识水平与了解，在使用 gcc 进行编译时应该是存在默认链接的，所以仅使用`-o`编译选项就能完成编译并生成可执行文件。
我认为本 Linux 命令手册现阶段仅侧重于命令功能说明，而非命令“实际原理”说明。如果要完成“实际原理”说明工作，我认为或许需要另外单独撰写一份《gcc 命令手册》。
如果我的理解有误，麻烦你及时提出并修正，并且希望可以继续探讨 :-)

**Comment by huaji0353** [comment]
@jaywcjlove 其实写个小提示就好了，比如这样 .o实际是需要一堆crt等lib的链接才能编译完成，win下可能需要链接kernel32等库

**Comment by huaji0353** [comment]
@huckhuang 不敢当不敢当，刚学编译原理的newbie，大佬还请多指教 :)
这是我的一个小实验，环境win
先写一个无head的void main(){}
然后照词条上的单纯 -c 然后 -o，全局-v输出debug output
gcc: warning: test.obj: linker input file unused because linking not done
In function `main':/home/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain@16'
实际上并不能编译成功。
或者加上这些参数（转自tinype）
-m32 -mconsole -s -Os -fno-ident -fno-stack-protector -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables -falign-functions=1 -mpreferred-stack-boundary=2 -falign-jumps=1 -falign-loops=1 -nostdlib -nodefaultlibs -nostartfiles -o test.exe test.obj
想当年新手上路玩curses一直不理解老是编译失败 也没前辈教导，折腾半天结果加个-lcurses就好了，坑啊

**Comment by huaji0353** [comment]
@huckhuang 我尝试了一下某在线编译器 的确可以编译通过 本机evn没问题，难道是mg版本(4.7.2)太老？

**Comment by huckhuang** [comment]
@huaji0353 
你这个 MinGW 版本确实有些老了，我觉得至少要用4.9，尽量使用较新的版本。
