### ISSUE TITLE
希望添加7z命令

### ISSUE THREAD

**Issue by Whichbfj28** [jaywcjlove/linux-command#476]
希望添加7z命令

**Comment by jaywcjlove** [comment]
@Whichbfj28 希望提供相关文档，或者提交 PR

**Comment by conglinyizhi** [comment]
#403  这个分支已经创建了 7z 指令，是因为什么原因没有搜索到吗？如果目前的结果满意，还请您关闭这个 issues，谢谢

**Comment by jaywcjlove** [comment]
@conglinyizhi 我没有看到
