### ISSUE TITLE
请求添加pwdx命令

### ISSUE THREAD

**Issue by LinuxZilong** [jaywcjlove/linux-command#484]
pwdx命令在工作中使用频繁，恳求添加命令。下面附man下的命令解读

PWDX(1)                          User Commands                         PWDX(1)
NAME
       pwdx - report current working directory of a process

SYNOPSIS
       pwdx [options] pid [...]

OPTIONS
       -V, --version
              Output version information and exit.
       -h, --help
              Output help screen and exit.
SEE ALSO
       ps(1), pgrep(1)

STANDARDS
       No standards apply, but pwdx looks an awful lot like a SunOS command.

AUTHOR
       Nicholas Miell ⟨nmiell@gmail.com⟩ wrote pwdx in 2004.

REPORTING BUGS
       Please send bug reports to ⟨procps@freelists.org⟩

procps-ng                          June 2011                           PWDX(1)
 Manual page pwdx(1) line 1/32 (END) (press h for help or q to quit)

------------
此命令用法很简单，但是常常会和pidof组合使用，例如： pwdx `pidof nginx`

**Comment by jaywcjlove** [comment]
@LinuxZilong 已添加，欢迎补充

**Comment by LinuxZilong** [comment]
已收到，另外请问：我的Docker环境下跑的容器，该如何跟上这些改动，是需要等待下一次镜像升级吗，我在重新拉一个容器

**Comment by jaywcjlove** [comment]
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/1680273/231363814-77f97d42-80c5-4b5c-951a-17e15c13020b.png">

```shell
$ docker pull wcjiang/linux-command:latest
```

@LinuxZilong CI 会自动将每次提交都发不到 docker 上，latest 是最新内容

**Comment by LinuxZilong** [comment]
谢谢你的解答，我正在pull 镜像

**Comment by conglinyizhi** [comment]
最新版本的网站已经发现了这个指令的帮助，能否请您关闭这个 issues 呢？
