### ISSUE TITLE
我想知道这个项目有没有限制使用规则的版本

### ISSUE THREAD

**Issue by conglinyizhi** [jaywcjlove/linux-command#489]
我想使用 ES6 的语法修改前端代码，但是看到代码的规范过于老旧，我想知道我是否可以进行类似这样的修改？

将其修改为更新规范的代码，使他们更易读，而且我也是想根据 markdown 文档生成一个目录，因为我看到有人需要快速访问到 实例，但是这一节在不同的文档中是不同的部分，有人需要快速跳转到实例

**Comment by jaywcjlove** [comment]
> 使用 ES6 的语法修改前端代码

@conglinyizhi 可以的，支持最新的 Safari  和 Chrome 即可

**Comment by conglinyizhi** [comment]
好的，马上动手
