### ISSUE TITLE
node build/compile.js编译后生成的路径有问题

### ISSUE THREAD

**Issue by liuyanchen1994** [jaywcjlove/linux-command#51]
从主页搜索可以，从搜索后再搜索就不行
![image](https://user-images.githubusercontent.com/19524048/45538763-855eda00-b83a-11e8-8d4c-a56c05c917fe.png)

**Comment by jaywcjlove** [comment]
@liuyanchen1994 不知道你改了什么代码，我的可以，没有毛病。

**Comment by liuyanchen1994** [comment]
什么代码都没有修改，clone下来 npm install了一下，然后node build/compile.js部署就不行，是少了什么步骤么

**Comment by liuyanchen1994** [comment]
> @liuyanchen1994 不知道你改了什么代码，我的可以，没有毛病。

什么代码都没有修改，clone下来 npm install了一下，然后node build/compile.js部署就不行，是少了什么步骤么

**Comment by jaywcjlove** [comment]
@liuyanchen1994 我的是 Mac 平台，你的是 Windows，现在没有办法查看windows系统下面的兼容，

你看看我生成出来的 https://git.io/linux 是不是也有同样的问题？
目前我在Mac 下面没有问题

**Comment by jaywcjlove** [comment]
生成的数据索引在 `.deploy/dt.js` 目录下，你看是不是生成的数据问题？

**Comment by huckhuang** [comment]
环境：
- 系统：Windows 10
- Node.js：8.11.3

![image](https://user-images.githubusercontent.com/23023193/45553900-aee22a80-b867-11e8-894a-9ea225f044be.png)

似乎生成的数据有问题。

**Comment by huckhuang** [comment]
https://github.com/jaywcjlove/linux-command/blob/4a2e116354873fc8f952ddc18e0cac94f8406679/template/js/index.js#L80

还有一个就是 root path 的问题，问题出现在上述该行。

当搜索框输入 `d` 时为下图所示情况：

![image](https://user-images.githubusercontent.com/23023193/45554592-64fa4400-b869-11e8-95e6-4903127275b3.png)

是不是应该把变量 `root_path` 中尾部的 `cd.html` 去掉才是理想的变量 `rootp` 的值？

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/linux-command/blob/master/build/compile.js#L275-L276

```js
json["p"] = md_path.replace(/\.md$/, '').replace(path_md, '').replace(/\\/g, '/');
```
这里替换一下

```js
.replace(/\\/g, '/')
```

**Comment by huckhuang** [comment]
https://github.com/jaywcjlove/linux-command/blob/4a2e116354873fc8f952ddc18e0cac94f8406679/template/js/index.js#L10-L15

获取根路径是不是也有问题？

**Comment by jaywcjlove** [comment]
@huckhuang 没有问题吧，搜索好像没有问题的样子

**Comment by huckhuang** [comment]
数据生成的问题解决了。

不过，在 Windows 下生成的命令详情页的搜索有问题。
比如在 `cd` 命令搜索 `su` ，`su` 的超链接是 `<domain>/c/cd.html/c/su.html`

https://github.com/jaywcjlove/linux-command/blob/4a2e116354873fc8f952ddc18e0cac94f8406679/template/js/index.js#L80

将该行修改为

```javascript
var rootp = this.root_path.replace(/\/$/, '').replace(/\/c\/\w+\.html/, '');
```

可解决问题，你尝试一下在你那边是否会造成异常。

**Comment by jaywcjlove** [comment]
@huckhuang 修改之后没有任何问题。

**Comment by huckhuang** [comment]
现在命令页没有问题了，但是首页搜索结果的超链接有问题。
例如在 `<domain>/index.html` 搜索 `cd`，得到的超链接是 `<domain>/index.html/c/cd.html`。
不知道你那边是否有这种情况。

https://github.com/jaywcjlove/linux-command/blob/683713f4b71c06206ce639926e9faae5122666ed/template/js/index.js#L14

考虑到除了 `index.html`，还有 `hot.html`，我尝试将该改行修改为

```javascript
return elm_path ? url.replace(/\/(c\/)?\w+\.html/, '').replace(/\/$/,''):'';
```

可以解决我遇到的问题。

**Comment by huckhuang** [comment]
@jaywcjlove 我用的就是 Windows，找到解决办法并测试通过了才跟你说的，毕竟要确保两边都没问题才行。 :smile:

**Comment by jaywcjlove** [comment]
@huckhuang 找机会重构一哈子，😆

**Comment by liuyanchen1994** [comment]
> @huckhuang 找机会重构一哈子，😆

问题解决了

**Comment by huckhuang** [comment]
@jaywcjlove 一看到重构，内心一颤，不知是激起了心中的热情，还是...（滑稽脸）

可以开个重构的 issue，构思一下方向、流程之类，我这边可以提供 Windows 的测试，有需要随时 at 我 😆

**Comment by jaywcjlove** [comment]
@huckhuang 待我有空重构一下和 `node.js` 编译😆
