### ISSUE TITLE
能不能问下为啥没有docker相关的命令呀？

### ISSUE THREAD

**Issue by tutianyu101** [jaywcjlove/linux-command#512]
能不能添加点docker的

**Comment by jaywcjlove** [comment]
- https://wangchujiang.com/reference/docs/docker.html
- https://wangchujiang.com/reference/docs/dockerfile.html

最早这个仓库是搜集 Linux 内部命令的，和常用的 Linux 命令，现在有更方便的地方搜集

**Comment by tutianyu101** [comment]
> * https://wangchujiang.com/reference/docs/docker.html
> * https://wangchujiang.com/reference/docs/dockerfile.html
> 
> 最早这个仓库是搜集 Linux 内部命令的，和常用的 Linux 命令，现在有更方便的地方搜集

所以大佬可以集成到静态页面里吗？现在静态页没有docker相关命令

**Comment by tutianyu101** [comment]
> * https://wangchujiang.com/reference/docs/docker.html
> * https://wangchujiang.com/reference/docs/dockerfile.html
> 
> 最早这个仓库是搜集 Linux 内部命令的，和常用的 Linux 命令，现在有更方便的地方搜集

要去别的网站查询有点麻烦

**Comment by jaywcjlove** [comment]
@tutianyu101 那欢迎添加 PR

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/reference/issues/102#issue-1451649637


这个网站你也可以部署一下 :)

**Comment by tutianyu101** [comment]
> @tutianyu101 那欢迎添加 PR

大佬PR是啥呀，问ai告诉我是个剪视频的软件，我该怎么添加docker命令呀？如果可以的话，请大佬告诉我

**Comment by tutianyu101** [comment]
> [jaywcjlove/reference#102 (comment)](https://github.com/jaywcjlove/reference/issues/102#issue-1451649637)
> 
> 这个网站你也可以部署一下 :)
> 
> @tutianyu101 已经将你的网站添加到 README.md 中了

大佬我提交更改申请了，添加了所有docker命令
![docker](https://github.com/jaywcjlove/linux-command/assets/134258491/14050ab4-a4c8-4804-bc24-ccf5985c75d0)

**Comment by jaywcjlove** [comment]
@tutianyu101 没有收到你的PR
