### ISSUE TITLE
大佬请更新下docker镜像，我今天新增的docker命令还没更新进去

### ISSUE THREAD

**Issue by tutianyu101** [jaywcjlove/linux-command#515]
大佬麻烦了

**Comment by jaywcjlove** [comment]
@tutianyu101 不是已经有了？ https://wangchujiang.com/linux-command/c/docker.html

**Comment by tutianyu101** [comment]
> @tutianyu101 不是已经有了？ https://wangchujiang.com/linux-command/c/docker.html

群主我在今天你回我后我就去更新版本了，发现没有，现在有了谢谢群主
