### ISSUE TITLE
tcpreplay.md 命令说明跟实际命令对不上

### ISSUE THREAD

**Issue by sfwwslm** [jaywcjlove/linux-command#546]
这个命令中的参数说明和 tcpreplay -h 和 man tcpreplay 都对不上。例如 -M 是指定回放的速率但是文档不知道说的是啥。

希望对tcpdump系列命令熟悉的大佬更新一下这些文档，谢谢。

这是我使用的版本信息
![image](https://github.com/jaywcjlove/linux-command/assets/77674552/2406b269-121b-478e-9960-145f2bae3670)

**Comment by jaywcjlove** [comment]
@sfwwslm 我基于 https://linux.die.net/man/1/tcpreplay 做了更新，你看看，欢迎 PR

**Comment by sfwwslm** [comment]
@jaywcjlove 好的，空的时候我会按 -h 提交一些PR
