### ISSUE TITLE
请问如何安装alfrd版本的呢？

### ISSUE THREAD

**Issue by hikitty2** [jaywcjlove/linux-command#55]
请问如何安装alfrd版本的呢？

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/linux-command/releases/tag/v1.0.0

下载 Linux.Command.alfredworkflow

**Comment by hikitty2** [comment]
> https://github.com/jaywcjlove/linux-command/releases/tag/v1.0.0
> 
> 下载Linux.Command.alfredworkflow

好的 谢谢
