### ISSUE TITLE
About the abbreviation

### ISSUE THREAD

**Issue by shangmingchao** [jaywcjlove/linux-command#56]
When we know "`pwd`" is the abbreviation of **"print work directory"**, it will be easy to remember. So it's a good idea to add "`rmdir`" -> **"remove directory"**,  "`chmod`" -> **"change mode"**, "`du`" -> **"disk usage"** and so on.

**Comment by huckhuang** [comment]
It is awesome to add these information into command's description. I find a simple and interesting way to do this. Just use a shield or badge.

Like this;
![pwd](https://img.shields.io/badge/pwd-print%20work%20directory-blue.svg)

We can add it between command name and its description.
```markdown
command
===

shield or badge here

description
```

For example:

```markdown
pwd
===

![pwd](https://img.shields.io/badge/pwd-print%20work%20directory-blue.svg)

....description
```

**Comment by shangmingchao** [comment]
I think it's nicely done. Thank you for your contribution.
