### ISSUE TITLE
Release v1.18.0 的 docset 包不对，尺寸只有10字节

### ISSUE THREAD

**Issue by vimiix** [jaywcjlove/linux-command#601]

**Comment by jaywcjlove** [comment]
@vimiix 感谢，我看到 CI 居然没有通过，我尝试解决一下

**Comment by jaywcjlove** [comment]
@vimiix 查看 v1.19.1 版本修复了这个问题

**Comment by vimiix** [comment]
> @vimiix 查看 v1.19.1 版本修复了这个问题

@jaywcjlove  Thanks, 导入 Dash 验证 OK。
