### ISSUE TITLE
web版本如何弄到自己的服务器呢？

### ISSUE THREAD

**Issue by hqylwrx** [jaywcjlove/linux-command#616]
web版本如何弄到自己的服务器呢？

**Comment by hqylwrx** [comment]
> @hqylwrx 这里说明了
> 
> https://github.com/jaywcjlove/linux-command/blob/2268588c603129baa8191f51a1e3230ae16ca04e/README.md?plain=1#L31-L35

好吧，我不会用clone命令克隆这个目录https://github.com/jaywcjlove/linux-command/tree/gh-pages到本地

**Comment by jaywcjlove** [comment]
切换到 https://github.com/jaywcjlove/linux-command/tree/gh-pages 分支下载静态页面，拷贝到你的静态资源服务器

**Comment by hqylwrx** [comment]
> 切换到 https://github.com/jaywcjlove/linux-command/tree/gh-pages 分支下载静态页面，拷贝到你的静态资源服务器

大神。。。我知道你估计很烦我， 我很菜。。。。

baidu i问的过程:

git clone https://github.com/jaywcjlove/linux-command.git
克隆完成后，您可以在本地仓库中找到gh-pages分支，并切换到该分支：

cd linux-command
git checkout gh-pages

git完不对啊。。。没找到 tree/gh-pages 目录啊。。。。

**Comment by hqylwrx** [comment]
算了，直接打包https://codeload.github.com/jaywcjlove/linux-command/zip/refs/heads/gh-pages下载zip 好了。。。太菜了我。。
