### ISSUE TITLE
Alfred版本使用

### ISSUE THREAD

**Issue by Yiyilinlin** [jaywcjlove/linux-command#72]
你好，请问Alfred的workflow是只能在线查询吗？如果可以离线查询的话，是需要编译下载下来的代码还是设置一下呢。

**Comment by jaywcjlove** [comment]
当初设计，离线发版好麻烦，所以在线查， 你可以改代码编译自己的版本。

**Comment by Yiyilinlin** [comment]
好的，我去尝试一下，谢谢，这个项目很好。
