### ISSUE TITLE
Krunner 插件支持

### ISSUE THREAD

**Issue by roachsinai** [jaywcjlove/linux-command#73]
我想写一个KDE平台的插件，但是不清楚如何访问这个网址`https://wangchujiang.com/linux-command/#!kw=ab`比如提供的关键字为`ab`如何得到对应的查询结果？好像结果只支持异步显示。

**Comment by roachsinai** [comment]
emm,看了alfred好像是获取的https://raw.githubusercontent.com/jaywcjlove/linux-command/master/dist/data.json这个文件，是这样？

**Comment by jaywcjlove** [comment]
@roachsinai 嗯是的这是个配置文件

**Comment by roachsinai** [comment]
谢谢。不过这个看了一下延迟有点儿高啊。。

**Comment by jaywcjlove** [comment]
@roachsinai 网络问题，可以把配置放到本地这样估计很快。

**Comment by roachsinai** [comment]
## [Krunner 版本](https://github.com/roachsinai/krunner-linuxcommands)

`Ctrl+j/k` 在匹配候选列表中进行选择。按下`Enter`之后在浏览器中打开对应命令的链接，并复制命令名字到剪切板。

![Imgur](https://i.imgur.com/SWBUmkt.png)

**Comment by jaywcjlove** [comment]
@roachsinai 已经添加到 README 中。6cd38ed

**Comment by roachsinai** [comment]
Ok, thanks.
