### ISSUE TITLE
【建议】：Mac版本App支持复制粘贴

### ISSUE THREAD

**Issue by rexlin600** [jaywcjlove/linux-command#76]
如题，Mac版本App不支持复制粘贴，有时候个人需要做笔记的时候希望不要屏蔽此功能，影响不大

**Comment by jaywcjlove** [comment]
你的issue可以在这里提 https://github.com/haloislet/linux-command

Mac版本不是 @haloislet  做的。 #35

**Comment by jaywcjlove** [comment]
可以去 #35 里面讨论，issue关了，我开启  #35
