### ISSUE TITLE
添加workflow后，使用时错误

### ISSUE THREAD

**Issue by guiqide** [jaywcjlove/linux-command#82]
安装插件后，在alfred下开启debug显示如果错误：

Starting debug for 'Linux Command'

[2019-04-28 14:24:30][ERROR: input.scriptfilter] Code 134: dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.60.dylib
  Referenced from: /usr/local/bin/node
  Reason: image not found
/bin/bash: line 2: 80451 Abort trap: 6           /usr/local/bin/node  <<-'CODE'
require("./linux")("c");
CODE

请问这是因为node不支持es2015语法吗？

**Comment by jaywcjlove** [comment]
@guiqide 支持的，上面说你的 `image ` 不存在啊

**Comment by guiqide** [comment]
@jaywcjlove 但我安装完这个：alfred包后还需要安装其他包吗？这个image是什么包？

**Comment by guiqide** [comment]
@jaywcjlove 
但我其他的workflow都可以用，我安装完alfred包后还需要安装其他依赖吗？，比如这个image

**Comment by jaywcjlove** [comment]
@guiqide   Alfred 依赖 node.js 因为里面的脚本是 node.js 写的。

**Comment by guiqide** [comment]
@jaywcjlove 我用nvm做node版本控制，当前nodejs版本为：v8.9.4

**Comment by jaywcjlove** [comment]
@guiqide 参考 #74，尝试解决问题。
