### ISSUE TITLE
文件传输里面少了scp

### ISSUE THREAD

**Issue by lijinghuatongxue** [jaywcjlove/linux-command#92]

**Comment by jaywcjlove** [comment]
没有明白什么意思 @lijinghuatongxue

**Comment by lijinghuatongxue** [comment]
![1557112703692](https://user-images.githubusercontent.com/17118790/57205348-ad30c700-6ff0-11e9-950c-5ed816951f9f.jpg)

**Comment by jaywcjlove** [comment]
@lijinghuatongxue thx! 👍
