### ISSUE TITLE
https://github.com/jaywcjlove/linux-command/edit/master/command/grep.md

### ISSUE THREAD

**Issue by runyu12345** [jaywcjlove/linux-command#97]
grep （global search regular expression(RE) and print out the line，全面搜索正则表达式并把行打印出来）是一种强大的文本搜索工具，它能使用正则表达式搜索文本，并把匹配的行打印出来。用于过滤/搜索的特定字符。**可使用正则表达式能多种命令配合使用**，使用上十分灵活。

这里有个错别字.

**Comment by jaywcjlove** [comment]
@runyu12345 欢迎 PR。哪个错别字呢？

**Comment by ZhuangZhu-74** [comment]
他说的意思大概是 加粗部分 改为 “正则表达式能配合多种命令使用”，原文表达是有些问题。
